### ISSUE TITLE
Add validation as property

### ISSUE THREAD

**Issue by Handers85** [Bunlong/react-barcodes#8]
In the jsbarcode package, on which this package is based, there is a property called valid. All other properties are already available, except valid. Below is an example of how valid is set when creating EAN13. 

```
	_createClass(EAN13, [{
		key: 'valid',
		value: function valid() {
			return this.data.search(/^[0-9]{13}$/) !== -1 && +this.data[12] === checksum(this.data);
		}
	},
```

Feel free to take a look at this. If it requires more than using the one available in jsbarcode, I am happy to help. 

I also noticed you've removed it in your d.ts file
```
  marginBottom?: number;
  marginLeft?: number;
  marginRight?: number;
  flat?: boolean;
  // valid?: Function; <----- Commented, probably for a good reason
```

**Comment by Handers85** [comment]
I think it basically comes down to this. I want to be able to set the valid callback option in order to display for the user what's wrong instead of breaking my app :)

```
	// If the input is not valid for the encoder, throw error.
	// If the valid callback option is set, call it instead of throwing error
	if (!encoder.valid()) {
		throw new _exceptions.InvalidInputException(encoder.constructor.name, text);
	}
```

**Comment by Handers85** [comment]
I tried to uncomment 'valid' in your package ts-file and it works perfectly. Any reason why you removed it?

**Comment by Bunlong** [comment]
@Handers85 Could you please help to make a pull request? Thanks!
